spring:
  application:
    name: cs_api

  mvc:
    problemdetails:
      enabled: true

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 10
        max-page-size: 100

  profiles:
    active: dev

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem

jwt:
  access-token:
    expiration-minutes: 15

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:4200}

management:
  endpoint:
    health:
      show-details: always

server:
  servlet:
    context-path: "/api"