spring:
  application:
    name: cs_api

  profiles:
    active: dev

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem

jwt:
  access-token:
    expiration-minutes: 15
