spring:
  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  docker:
    compose:
      enabled: false

  datasource:
    url: ${DB_PROD_URL:jdbc:postgresql://localhost:5432/controle-smart-prod}
    username: ${DB_PROD_USER:${DATABASE_USERNAME:postgres}}
    password: ${DB_PROD_PASSWORD:${DATABASE_PASSWORD:postgres}}