-- Migration V1: Criação do Schema Master/Identity e Carga de Seeds Inicial
CREATE SCHEMA IF NOT EXISTS master;

-- 1. Tabela de Roles
CREATE TABLE IF NOT EXISTS master.roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255)
);

-- 2. Tabela de Permissões
CREATE TABLE IF NOT EXISTS master.permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255)
);

-- 3. Tabela de Junção Role_Permissions
CREATE TABLE IF NOT EXISTS master.role_permissions (
    role_id BIGINT NOT NULL REFERENCES master.roles(id) ON DELETE CASCADE,
    permission_id BIGINT NOT NULL REFERENCES master.permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

-- 4. Tabela de Usuários
CREATE TABLE IF NOT EXISTS master.users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone_number VARCHAR(50) NOT NULL UNIQUE,
    tenant_id UUID NULL,
    role_id BIGINT NOT NULL REFERENCES master.roles(id),
    status VARCHAR(20) NOT NULL,
    mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    mfa_secret VARCHAR(255) NULL,
    force_password_change BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL,
    deleted_at TIMESTAMP WITHOUT TIME ZONE NULL
);

-- 5. Tabela de Admins (Estratégia JOINED com a tabela users)
CREATE TABLE IF NOT EXISTS master.admins (
    user_id UUID PRIMARY KEY REFERENCES master.users(id) ON DELETE CASCADE,
    last_login TIMESTAMP WITHOUT TIME ZONE NULL,
    last_login_ip VARCHAR(45) NULL,
    last_login_user_agent VARCHAR(255) NULL,
    failed_login_attempts INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMP WITHOUT TIME ZONE NULL
);

-- 6. Tabela de Refresh Tokens
CREATE TABLE IF NOT EXISTS master.refresh_tokens (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES master.users(id) ON DELETE CASCADE,
    token VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- 7. Tabela de Audit Logs
CREATE TABLE IF NOT EXISTS master.audit_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid()
);

-- 8. Tabela de Tenants
CREATE TABLE IF NOT EXISTS master.tenants (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    slug VARCHAR(255) NOT NULL UNIQUE,
    trade_name VARCHAR(255) NOT NULL,
    corporate_name VARCHAR(255) NOT NULL,
    document VARCHAR(255) UNIQUE,
    email VARCHAR(255),
    phone_number VARCHAR(255),
    current_plan VARCHAR(50),
    status VARCHAR(50),
    is_exclusive_db BOOLEAN DEFAULT FALSE,
    database_url VARCHAR(255),
    schema_name VARCHAR(255),
    timezone TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL,
    deleted_at TIMESTAMP WITHOUT TIME ZONE NULL
);

-- 9. Tabela de Customizações dos Tenants
CREATE TABLE IF NOT EXISTS master.tenant_customizations (
    tenant_id UUID PRIMARY KEY REFERENCES master.tenants(id) ON DELETE CASCADE,
    logo_url VARCHAR(255),
    primary_color VARCHAR(50),
    secondary_color VARCHAR(50)
);

-- 10. Tabela do Spring Modulith para Publicação de Eventos JPA
CREATE TABLE IF NOT EXISTS event_publication (
    id UUID PRIMARY KEY,
    listener_id VARCHAR(512) NOT NULL,
    event_type VARCHAR(512) NOT NULL,
    serialized_event TEXT NOT NULL,
    publication_date TIMESTAMP WITH TIME ZONE NOT NULL,
    completion_date TIMESTAMP WITH TIME ZONE NULL
);

-- ==========================================
-- SEEDS: ROLES E PERMISSÕES INICIAIS
-- ==========================================

-- Inserir Roles
INSERT INTO master.roles (name, description) VALUES
    ('SYSTEM_ADMIN', 'Administrador do Sistema'),
    ('TENANT_ADMIN', 'Administrador da Empresa'),
    ('MANAGER', 'Gerente'),
    ('OPERATOR', 'Operador')
ON CONFLICT (name) DO NOTHING;

-- Inserir Permissões
INSERT INTO master.permissions (name, description) VALUES
    ('admin:create', 'Criar administradores do sistema'),
    ('admin:read', 'Visualizar administradores do sistema'),
    ('admin:update', 'Editar administradores do sistema'),
    ('admin:delete', 'Excluir administradores do sistema'),
    ('tenant:create', 'Criar empresas/tenants'),
    ('tenant:read', 'Visualizar empresas/tenants'),
    ('tenant:update', 'Editar empresas/tenants'),
    ('tenant:delete', 'Excluir empresas/tenants'),
    ('user:create', 'Criar usuários da empresa'),
    ('user:read', 'Visualizar usuários da empresa'),
    ('user:update', 'Editar usuários da empresa'),
    ('user:delete', 'Excluir usuários da empresa')
ON CONFLICT (name) DO NOTHING;

-- Mapeamento de Permissões para SYSTEM_ADMIN (Todas as permissões)
INSERT INTO master.role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM master.roles r
CROSS JOIN master.permissions p
WHERE r.name = 'SYSTEM_ADMIN'
ON CONFLICT DO NOTHING;

-- Mapeamento de Permissões para TENANT_ADMIN
INSERT INTO master.role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM master.roles r
JOIN master.permissions p ON p.name IN (
    'tenant:read', 'tenant:update',
    'user:create', 'user:read', 'user:update', 'user:delete'
)
WHERE r.name = 'TENANT_ADMIN'
ON CONFLICT DO NOTHING;

-- Mapeamento de Permissões para MANAGER
INSERT INTO master.role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM master.roles r
JOIN master.permissions p ON p.name IN (
    'tenant:read',
    'user:create', 'user:read', 'user:update'
)
WHERE r.name = 'MANAGER'
ON CONFLICT DO NOTHING;

-- Mapeamento de Permissões para OPERATOR
INSERT INTO master.role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM master.roles r
JOIN master.permissions p ON p.name IN (
    'tenant:read',
    'user:read'
)
WHERE r.name = 'OPERATOR'
ON CONFLICT DO NOTHING;
